In [1]:
import pandas as pd
import requests
import numpy as np

In [2]:
# Q1. Pandas version
pd.__version__

'2.2.3'

In [3]:
# Getting the data 1
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
dataset_path = '../datasets/'
response = requests.get(url)
with open(f'{dataset_path}laptops.csv', 'wb') as file:
    for chunk in response.iter_content(chunk_size=1024):
        file.write(chunk)

In [4]:
# Getting the data 2
laptops = pd.read_csv(f'{dataset_path}laptops.csv')

In [5]:
# Q2. Records count
# How many records are in the dataset?
laptops['Laptop'].size

2160

In [6]:
# Q3. Laptop brands
# How many laptop brands are presented in the dataset?
laptops['Brand'].nunique()

27

In [7]:
# Q4. Missing values
# How many columns in the dataset have missing values?
laptops.isnull().sum().unique()

array([   0,   42, 1371,    4])

In [8]:
# Q5. Maximum final price
# What's the maximum final price of Dell notebooks in the dataset?
dell_laptops = laptops.loc[laptops['Brand'].str.contains('Dell')]
print(dell_laptops['Final Price'].max())

3936.0


In [9]:
# Q6. Median value of Screen
# Find the median value of Screen column in the dataset.
median_value = laptops['Screen'].median()
print(median_value)

# Next, calculate the most frequent value of the same Screen column.
most_frequent_value = laptops['Screen'].mode().max()
print(most_frequent_value)

# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
laptops.fillna({'Screen': most_frequent_value}, inplace=True)

# Now, calculate the median value of Screen once again.
median_value2 = laptops['Screen'].median()
print(median_value2)

15.6
15.6
15.6


In [10]:
# Select all the "Innjoo" laptops from the dataset.
innjoo_laptops = laptops.loc[laptops['Brand'].str.contains('Innjoo')]
innjoo_laptops

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [11]:
# Select only columns RAM, Storage, Screen.
innjoo_laptops_rss = innjoo_laptops[['RAM', 'Storage', 'Screen']]
innjoo_laptops_rss

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [12]:
# Get the underlying NumPy array. Let's call it X.
x = innjoo_laptops_rss.to_numpy()
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [13]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
tx = x.T
tx

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [14]:
xtx = tx.dot(x)
xtx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [15]:
# Compute the inverse of XTX.
xtx_inv = np.linalg.inv(xtx)
xtx_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [16]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [17]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
xtx_inv_tx = xtx_inv.dot(x.T)
xtx_inv_tx

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [18]:
w = xtx_inv_tx.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [19]:
# What's the sum of all the elements of the result?
print(w.sum().round(3))

91.3
